steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      ENV_NAME: "testing"
      
  - trigger: "triggered-pipeline"
