steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      ENV_NAME: "testing"
      
  - wait
  
  - trigger: "triggered-pipeline"
    name: "trigger downstream pipeline"
    build:
      env:
        COMMIT_STRING : "${BUILDKITE_COMMIT}"
      message: |
        Triggered by: "${BUILDKITE_BUILD_URL}"
        Branch: "${BUILDKITE_BRANCH}"
        Created by: "${BUILDKITE_BUILD_CREATOR}"      
  
